version: '3.8'

services:
  server:
    image: lost-found-backend
    ports:
      - "5000:5000"
    networks:
      - lost-found

  client:
    image: lost-found-frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - lost-found

  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - lost-found
    volumes:
      - mongo-data:/data/db

networks:
  lost-found:
    driver: bridge

volumes:
  mongo-data:
    driver: local 